/**
 * Maps lowercase country names (and common aliases) to ISO 3166-1 alpha-2 codes.
 * Keys are sorted longest-first at lookup time to handle "south africa" before "africa".
 */
const COUNTRY_MAP = {
  // ── Africa ──────────────────────────────────────────────────────────────────
  nigeria: 'NG',
  benin: 'BJ',
  ghana: 'GH',
  kenya: 'KE',
  'south africa': 'ZA',
  egypt: 'EG',
  ethiopia: 'ET',
  tanzania: 'TZ',
  uganda: 'UG',
  rwanda: 'RW',
  cameroon: 'CM',
  'ivory coast': 'CI',
  "cote d'ivoire": 'CI',
  "côte d'ivoire": 'CI',
  senegal: 'SN',
  mali: 'ML',
  'burkina faso': 'BF',
  niger: 'NE',
  'democratic republic of congo': 'CD',
  'democratic republic of the congo': 'CD',
  'dr congo': 'CD',
  drc: 'CD',
  angola: 'AO',
  mozambique: 'MZ',
  zimbabwe: 'ZW',
  zambia: 'ZM',
  malawi: 'MW',
  madagascar: 'MG',
  somalia: 'SO',
  sudan: 'SD',
  'south sudan': 'SS',
  libya: 'LY',
  tunisia: 'TN',
  morocco: 'MA',
  algeria: 'DZ',
  gabon: 'GA',
  'republic of congo': 'CG',
  'republic of the congo': 'CG',
  congo: 'CG',
  guinea: 'GN',
  'sierra leone': 'SL',
  liberia: 'LR',
  togo: 'TG',
  botswana: 'BW',
  namibia: 'NA',
  mauritius: 'MU',
  'cape verde': 'CV',
  'cabo verde': 'CV',
  seychelles: 'SC',
  eritrea: 'ER',
  djibouti: 'DJ',
  comoros: 'KM',
  lesotho: 'LS',
  swaziland: 'SZ',
  eswatini: 'SZ',
  'equatorial guinea': 'GQ',
  'central african republic': 'CF',
  chad: 'TD',
  mauritania: 'MR',
  gambia: 'GM',
  'guinea-bissau': 'GW',
  'guinea bissau': 'GW',
  'sao tome and principe': 'ST',
  burundi: 'BI',
  'western sahara': 'EH',

  // ── Europe ───────────────────────────────────────────────────────────────────
  'united kingdom': 'GB',
  uk: 'GB',
  'great britain': 'GB',
  england: 'GB',
  france: 'FR',
  germany: 'DE',
  italy: 'IT',
  spain: 'ES',
  portugal: 'PT',
  netherlands: 'NL',
  belgium: 'BE',
  sweden: 'SE',
  norway: 'NO',
  denmark: 'DK',
  finland: 'FI',
  switzerland: 'CH',
  austria: 'AT',
  poland: 'PL',
  greece: 'GR',
  romania: 'RO',
  ukraine: 'UA',
  'czech republic': 'CZ',
  czechia: 'CZ',
  hungary: 'HU',
  serbia: 'RS',
  croatia: 'HR',
  slovakia: 'SK',
  bulgaria: 'BG',
  ireland: 'IE',
  'republic of ireland': 'IE',
  russia: 'RU',
  turkey: 'TR',
  luxembourg: 'LU',
  iceland: 'IS',
  malta: 'MT',
  cyprus: 'CY',
  albania: 'AL',
  'north macedonia': 'MK',
  'bosnia and herzegovina': 'BA',
  bosnia: 'BA',
  montenegro: 'ME',
  slovenia: 'SI',
  latvia: 'LV',
  lithuania: 'LT',
  estonia: 'EE',
  moldova: 'MD',
  belarus: 'BY',
  georgia: 'GE',
  armenia: 'AM',
  azerbaijan: 'AZ',
  kosovo: 'XK',

  // ── Americas ─────────────────────────────────────────────────────────────────
  'united states': 'US',
  'united states of america': 'US',
  usa: 'US',
  canada: 'CA',
  brazil: 'BR',
  mexico: 'MX',
  argentina: 'AR',
  colombia: 'CO',
  chile: 'CL',
  peru: 'PE',
  venezuela: 'VE',
  ecuador: 'EC',
  bolivia: 'BO',
  paraguay: 'PY',
  uruguay: 'UY',
  cuba: 'CU',
  haiti: 'HT',
  'dominican republic': 'DO',
  jamaica: 'JM',
  'trinidad and tobago': 'TT',
  trinidad: 'TT',
  barbados: 'BB',
  bahamas: 'BS',
  'costa rica': 'CR',
  panama: 'PA',
  guatemala: 'GT',
  honduras: 'HN',
  'el salvador': 'SV',
  nicaragua: 'NI',
  belize: 'BZ',
  guyana: 'GY',
  suriname: 'SR',

  // ── Asia & Oceania ────────────────────────────────────────────────────────────
  india: 'IN',
  china: 'CN',
  japan: 'JP',
  'south korea': 'KR',
  korea: 'KR',
  'north korea': 'KP',
  indonesia: 'ID',
  philippines: 'PH',
  vietnam: 'VN',
  thailand: 'TH',
  malaysia: 'MY',
  singapore: 'SG',
  australia: 'AU',
  'new zealand': 'NZ',
  pakistan: 'PK',
  bangladesh: 'BD',
  'sri lanka': 'LK',
  nepal: 'NP',
  myanmar: 'MM',
  cambodia: 'KH',
  laos: 'LA',
  mongolia: 'MN',
  'saudi arabia': 'SA',
  uae: 'AE',
  'united arab emirates': 'AE',
  israel: 'IL',
  iraq: 'IQ',
  iran: 'IR',
  jordan: 'JO',
  lebanon: 'LB',
  qatar: 'QA',
  kuwait: 'KW',
  bahrain: 'BH',
  oman: 'OM',
  yemen: 'YE',
  afghanistan: 'AF',
  kazakhstan: 'KZ',
  uzbekistan: 'UZ',
  taiwan: 'TW',
  'hong kong': 'HK',
  'papua new guinea': 'PG',
  fiji: 'FJ',
};

/**
 * Returns all [name, code] pairs sorted by name length descending.
 * This guarantees "south africa" is checked before "africa".
 */
const SORTED_ENTRIES = Object.entries(COUNTRY_MAP).sort(
  (a, b) => b[0].length - a[0].length
);

/**
 * Finds the ISO-2 country code for a candidate string.
 * Tries longest possible match first.
 * @param {string} candidate  Lowercased phrase after "from" or "in"
 * @returns {string|null}
 */
function findCountryCode(candidate) {
  const words = candidate.trim().split(/\s+/);
  // Try progressively shorter slices (longest-first)
  for (let len = words.length; len >= 1; len--) {
    const phrase = words.slice(0, len).join(' ');
    const code = COUNTRY_MAP[phrase];
    if (code) return code;
  }
  return null;
}

module.exports = { COUNTRY_MAP, SORTED_ENTRIES, findCountryCode };
